# Generated by Django 4.2.4 on 2023-08-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lost_item_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('lost_date', models.DateField()),
                ('lost_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('additional_comments', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='lost_items/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
