# Generated by Django 4.2.4 on 2023-08-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_item_details',
            name='additional_comments',
            field=models.TextField(blank=True, default='---'),
        ),
    ]
