# Generated by Django 4.2.4 on 2023-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostItem', '0004_alter_lost_item_details_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lost_item_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='lost_items/'),
        ),
    ]
