# Generated by Django 4.2.4 on 2023-09-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostItem', '0008_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
    ]
