# Generated by Django 4.2.4 on 2023-09-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoundedItem', '0004_alter_founded_items_details_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founded_items_details',
            old_name='lost_date',
            new_name='founded_date',
        ),
        migrations.RenameField(
            model_name='founded_items_details',
            old_name='lost_time',
            new_name='founded_time',
        ),
    ]
